=== Abcow/Forensic-Pathology-Teaching-Tool/Content/page.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com" elementFormDefault="qualified">
    
    <xs:element name="page">
        <xs:complexType name="container">
            <xs:choice maxOccurs="unbounded">

                <xs:element name="title" type="xs:string" />

                <xs:element name="subtitle" type="xs:string" />

                <xs:element name="text" type="xs:string" />

                <xs:element ref="image" />

                <xs:element name="gallery">
                    <xs:complexType>
                        
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="image" minOccurs="1" />
                        </xs:sequence>

                        <xs:attribute name="width">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="height">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>

                <xs:element name="tabs">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="tab" minOccurs="1">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="container">
                                            <xs:attribute name="name" type="xs:string" default="" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="popup-button">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="container">
                                <xs:attribute name="text" type="xs:string" default="" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="padding">
                    <xs:complexType>
                        <xs:attribute name="height">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="1" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <xs:element name="padding">
                    <xs:element name="navigation-button">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="destination" type="xs:string" use="required" />
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:element>

                <xs:element name="video" type="media" />

                <xs:element name="audio">
                    <xs:complexType>
                        <xs:attribute name="filename" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="columns">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="column" minOccurs="1" type="container" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


                <xs:element name="csi-image">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="click-area">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="container">
                                            <xs:attribute name="x1"  use="required" type="percentage" />
                                            <xs:attribute name="y1"  use="required" type="percentage" />
                                            <xs:attribute name="x2"  use="required" type="percentage" />
                                            <xs:attribute name="y2"  use="required" type="percentage" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="image">
        <xs:complexType name="media">

            <xs:attribute name="filename" type="xs:string" use="required" />

            <xs:attribute name="width">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

            <xs:attribute name="height">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

        </xs:complexType>
    </xs:element>

    <xs:simpleType name="percentage">
        <xs:restriction base="xs:string">
            <xs:pattern value="^([0-9]|[1-9][0-9]|100)%$"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/Q3.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" prev="Q2" next="Q4">
	<title>These are links to different Questions</title>
	<!-- Buttons to different questions & galleries -->
	<navigation-button destination="Q1">Question 1</navigation-button>
	<navigation-button destination="Q2">Question 2</navigation-button>
	<navigation-button destination="Q3">Question 3</navigation-button>
	<navigation-button destination="Q4">Question 4</navigation-button>
	
	<!-- The Galleries -->
	<gallery width="700" height="600">
		<image filename="bunny.jpg" />
		<image filename="bunny-2.jpg" />
		<image filename="bunny-3.jpg" />
		<image filename="bunny-4.jpg" />
	</gallery>
		
	<!-- The Question -->	
	<title>Question 3</title>
    <popup-button text="iUOHclskj">
        <subtitle>Incorrect!</subtitle>
    </popup-button>

    <popup-button text="oyd98qoguijdna77">
        <subtitle>Incorrect</subtitle>
    </popup-button>

    <popup-button text="8oughviualhjkx asud">
        <subtitle>Incorrect</subtitle>
    </popup-button>

    <popup-button text="aaaaaaaaaaaaa">
        <subtitle>Correct!</subtitle>
    </popup-button>

</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/Q4.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" prev="Q3">

	<title>These are links to different questions!</title>
	<!-- Buttons to different questions & galleries -->
	<navigation-button destination="Q1">Question 1</navigation-button>
	<navigation-button destination="Q2">Question 2</navigation-button>
	<navigation-button destination="Q3">Question 3</navigation-button>
	<navigation-button destination="Q4">Question 4</navigation-button>
	
	<!-- The Galleries -->
	<gallery width="700" height="600">
		<image filename="4.png" />
		<image filename="5.png" />
		<image filename="bunny.jpg" />
	</gallery>
		
	<!-- The Question -->	
	<title>Question 1</title>
    <popup-button text="Random text">
        <subtitle>Incorrect!</subtitle>
    </popup-button>

    <popup-button text="More random text">
        <subtitle>Incorrect</subtitle>
    </popup-button>

    <popup-button text="more random textx20">
        <subtitle>Incorrect</subtitle>
    </popup-button>

    <popup-button text="hpidhasjidhaspdoj">
        <subtitle>Correct!</subtitle>
    </popup-button>

</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/gallery1.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" next="tabbedGallery" prev="home">
	<title>This is a human head</title>
	<subtitle>It's pretty gross</subtitle>
	<gallery width="800" height="600">
		<image filename="bun.jpg" />
		<image filename="butt.jpg" />
		<image filename="bunny.jpg" />
	</gallery>
	<text>The human head is an interesting organ. Scroll the pages to see different views of this exciting spectacle of human life.</text>
</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/Q2.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" prev="Q1" next="Q3">
	
	
	<title>These are links to different questions!</title>
	<!-- Buttons to different questions & galleries -->
	<navigation-button destination="Q1">Question 1</navigation-button>
	<navigation-button destination="Q2">Question 2</navigation-button>
	<navigation-button destination="Q3">Question 3</navigation-button>
	<navigation-button destination="Q4">Question 4</navigation-button>
	
	<!-- The Galleries -->
	<gallery width="700" height="600">
				<image filename="butt.jpg" />
			</gallery>
		
	<!-- The Question -->	
	<title>Question 2</title>
    <popup-button text="Bunnies">
        <subtitle>Incorrect!</subtitle>
    </popup-button>

    <popup-button text="2 Bunnies">
        <subtitle>Incorrect</subtitle>
    </popup-button>

    <popup-button text="3 Bunnies">
        <subtitle>Incorrect</subtitle>
    </popup-button>

    <popup-button text="4 Bunnies">
        <subtitle>Correct!</subtitle>
    </popup-button>

</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/quizExample.xml
<?xml version="1.0" encoding="utf-8"?>

<page
    xmlns="http://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3schools.com page.xsd"
    previous="example">

    <title>What is the capital of Germany?</title>
    <popup-button text="Munich">
        <subtitle>Incorrect!</subtitle>
        <text>Munich is the third largest city in Germany.</text>
    </popup-button>

    <popup-button text="Berlin">
        <title>Correct!</title>
    </popup-button>

    <popup-button text="The letter G">
        <text>Correct...I ...guess... Not really what we were looking for.</text>
    </popup-button>

    <popup-button text="Hamburg">
        <subtitle>Incorrect!</subtitle>
        <text>Hamburg is the second largest city in Germany.</text>
    </popup-button>

</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/2-gallery1.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" prev="1-video" next="3-tabbedGallery">
	<title>Gallery</title>
	<text>Look, an image gallery!</text>
	<subtitle>Bunnies</subtitle>
	<gallery width="700" height="600">
		<image filename="bun.jpg" />
		<image filename="butt.jpg" />
		<image filename="5.png" />
	</gallery>
</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/Q1.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" prev="home" next="Q2">
	
	<title>These are links to different questions!</title>
	<!-- Buttons to different questions & galleries -->
	<navigation-button destination="Q1">Question 1</navigation-button>
	<navigation-button destination="Q2">Question 2</navigation-button>
	<navigation-button destination="Q3">Question 3</navigation-button>
	<navigation-button destination="Q4">Question 4</navigation-button>
	
	<!-- The Galleries -->
	<gallery width="700" height="600">
		<image filename="bun.jpg" />
		<image filename="butt.jpg" />
		<image filename="5.png" />
	</gallery>
		
	<!-- The Question -->	
	<title>Question 1</title>
    <popup-button text="Butterflys">
        <subtitle>Incorrect!</subtitle>
    </popup-button>

    <popup-button text="2 Butterflys">
        <subtitle>Incorrect</subtitle>
    </popup-button>

    <popup-button text="3 Butterflys">
        <subtitle>Incorrect</subtitle>
    </popup-button>

    <popup-button text="4 Butterflys">
        <subtitle>Correct!</subtitle>
    </popup-button>

</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/4-quizExample.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" prev="3-tabbedGallery" next="5-quiz" >

    <title>What is the capital of Germany?</title>

    <popup-button text="Munich">
        <subtitle>Incorrect!</subtitle>
        <text>Munich is the third largest city in Germany.</text>
    </popup-button>

    <popup-button text="Berlin">
        <title>Correct!</title>
    </popup-button>

    <popup-button text="The letter G">
        <text>Correct...I ...guess... Not really what we were looking for.</text>
    </popup-button>

    <popup-button text="Hamburg">

        <subtitle>Incorrect!</subtitle>

        <text>Hamburg is the second largest city in Germany.</text>

    </popup-button>

    <subtitle>Another way to organise the buttons</subtitle>

    <columns>

        <column>
            <popup-button text="Munich">

                <subtitle>Incorrect!</subtitle>

                <text>Munich is the third largest city in Germany.</text>

            </popup-button>
        </column> 

        <column>
            <popup-button text="Berlin">
                <title>Correct!</title>
            </popup-button>
        </column>

        <column>
            <popup-button text="The letter G">
                <text>Correct...I ...guess... Not really what we were looking for.</text>
            </popup-button>
        </column>

        <column>
            <popup-button text="Hamburg">

                <subtitle>Incorrect!</subtitle>

                <text>Hamburg is the second largest city in Germany.</text>
                
            </popup-button>
        </column>

    </columns>

</page>
