=== Abcow/Forensic-Pathology-Teaching-Tool/Content/page.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com" elementFormDefault="qualified">
    
    <xs:element name="page">
        <xs:complexType name="container">
            <xs:choice maxOccurs="unbounded">

                <xs:element name="title" type="xs:string" />

                <xs:element name="subtitle" type="xs:string" />

                <xs:element name="text" type="xs:string" />

                <xs:element ref="image" />

                <xs:element name="gallery">
                    <xs:complexType>
                        
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="image" minOccurs="1" />
                        </xs:sequence>

                        <xs:attribute name="width">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="height">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>

                <xs:element name="tabs">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="tab" minOccurs="1">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="container">
                                            <xs:attribute name="name" type="xs:string" default="" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="popup-button">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="container">
                                <xs:attribute name="text" type="xs:string" default="" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="padding">
                    <xs:complexType>
                        <xs:attribute name="height">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="1" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <xs:element name="padding">
                    <xs:element name="navigation-button">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="destination" type="xs:string" use="required" />
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:element>

                <xs:element name="video" type="media" />

                <xs:element name="audio">
                    <xs:complexType>
                        <xs:attribute name="filename" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="columns">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="column" minOccurs="1" type="container" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


                <xs:element name="csi-image">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="click-area">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="container">
                                            <xs:attribute name="x1"  use="required" type="percentage" />
                                            <xs:attribute name="y1"  use="required" type="percentage" />
                                            <xs:attribute name="x2"  use="required" type="percentage" />
                                            <xs:attribute name="y2"  use="required" type="percentage" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="image">
        <xs:complexType name="media">

            <xs:attribute name="filename" type="xs:string" use="required" />

            <xs:attribute name="width">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

            <xs:attribute name="height">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

        </xs:complexType>
    </xs:element>

    <xs:simpleType name="percentage">
        <xs:restriction base="xs:string">
            <xs:pattern value="^([0-9]|[1-9][0-9]|100)%$"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/3-tabbedGallery.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd"  prev="2-gallery1" next="4-quizExample">
	<title>Gallery</title>
	<text>This is all the different Information from your case, review it here in this great format</text>
<tabs>
		<tab name="Bunnies">
			<subtitle>Bunnies</subtitle>
			<gallery width="700" height="600">
				<image filename="bun.jpg" />
				<image filename="butt.jpg" />
				<image filename="5.png" />
			</gallery>
		</tab>
		<tab name="Butterflys">
			<subtitle>Butterflys</subtitle>
			<gallery width="700" height="600">
				<image filename="butt.jpg" />
			</gallery>
		</tab>
		<tab name="A French Man">
			<subtitle>A French Man</subtitle>
			<gallery width="700" height="600">
				<image filename="bunny.jpg" />
				<image filename="bunny-2.jpg" />
				<image filename="bunny-3.jpg" />
				<image filename="bunny-4.jpg" />
			</gallery>
		</tab>
		<tab name="Something Really Cool">
			<subtitle>Something Really Cool</subtitle>
			<gallery width="700" height="600">
				<image filename="4.png" />
				<image filename="5.png" />
				<image filename="bunny.jpg" />
			</gallery>
		</tab>

</tabs>
</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/home.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" next="1-video">
	<title>Forensic Pathology Teaching Tool</title>
	<subtitle>About this Project</subtitle>
	<padding height="10" />
	<text>Big Padding</text>
	<padding height="10" />
	<text>This resource has been created to give you a basic understanding of forensic pathology. It will guide you through the forensic process from the initial crime scene to the autopsy, toxicology and histology.</text>
	<padding height="0.5" />
	<text>Little Padding</text>
	<padding height="0.5" />
	<text>Following this guidance you will begin your own case, trying to ascertain the cause of death. I hope you enjoy using this as much as we did making it.</text>
	<image filename="0.jpg" width="800" />
	<columns>

		<column>
			<navigation-button destination="6-horsequiz">A link to the end!</navigation-button>
		</column>

		<column>
			<navigation-button destination="3-tabbedGallery">A link to the middle!</navigation-button>
		</column>

	</columns>
</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/quiz.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" next="quizExample" prev="home">
	<title>Quiz</title>
	<text>Scroll down to see the quiz, we've provided the gallery for some help too</text>
<tabs>
		<tab name="Bunnies">
			<subtitle>Bunnies</subtitle>
			<gallery width="700" height="600">
				<image filename="bun.jpg" />
				<image filename="butt.jpg" />
				<image filename="5.png" />
			</gallery>
		</tab>
		<tab name="Butterflys">
			<subtitle>Butterflys</subtitle>
			<gallery width="700" height="600">
				<image filename="butt.jpg" />
			</gallery>
		</tab>
		<tab name="A French Man">
			<subtitle>A French Man</subtitle>
			<gallery width="700" height="600">
				<image filename="bunny.jpg" />
				<image filename="bunny-2.jpg" />
				<image filename="bunny-3.jpg" />
				<image filename="bunny-4.jpg" />
			</gallery>
		</tab>
		<tab name="Something Really Cool">
			<subtitle>Something Really Cool</subtitle>
			<gallery width="700" height="600">
				<image filename="4.png" />
				<image filename="5.png" />
				<image filename="bunny.jpg" />
			</gallery>
		</tab>

	</tabs>

	<title>What's that man holding?</title>
    <popup-button text="Butterflys">
        <subtitle>Incorrect!</subtitle>
        <text>No he isn't, this is a butterfly</text>
        <image filename="butt.jpg"/>
    </popup-button>

    <popup-button text="A human head">
        <subtitle>No!</subtitle>
        <text>No, that would be insane. Who puts pictures like that in places?</text>
    </popup-button>

    <popup-button text="The letter G">
        <text>Who wrote this quiz?</text>
    </popup-button>

    <popup-button text="Hamburg">
        <subtitle>Correct!</subtitle>
        <text>Hamburg is the second largest city in Germany. Well done!</text>
    </popup-button>

</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/horsequiz.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd" prev="quiz">
	<subtitle>What is this sound?</subtitle>
	<audio />
    <popup-button text="A hourse">
        <subtitle>Correct!</subtitle>
        <text>You're clever, aren't you?</text>
    </popup-button>

    <popup-button text="A human head">
        <subtitle>No!</subtitle>
        <text>No, stop answering this!</text>
    </popup-button>

    <text>End of tool for now!</text>

</page>

=== Abcow/Forensic-Pathology-Teaching-Tool/Content/test.xml
<?xml version="1.0" encoding="utf-8"?>

<page xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com page.xsd">
	<title>This is a title.</title>
	<subtitle>This is a subtitle.</subtitle>
	<text>This is some text...Sed scelerisque, eros vel tincidunt euismod, eros erat pharetra nisl, id mattis elit arcu varius tellus. Suspendisse laoreet elit ac diam hendrerit, quis sollicitudin nisi maximus. In ornare urna ut dui bibendum tincidunt. Fusce vitae ante tincidunt, fermentum orci in, sodales dui. Aliquam et tellus enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vehicula nisl eget lectus scelerisque, sed sodales erat dapibus. Morbi vel tellus eros. Maecenas lacinia nibh sed finibus rhoncus. Suspendisse enim leo, tempor eget tempor eget, molestie in felis. In id diam velit. Cras ex nisl, porttitor quis auctor non, lacinia id ligula. Cras lacinia orci a nunc rhoncus pretium. Quisque rhoncus orci at lectus pretium dapibus. Nulla blandit quam nec auctor sagittis.</text>
	<image filename="icon.ico" width="64" height="64" />
	<gallery width="256" height="256">
		<image filename="0.jpg" />
		<image filename="1.jpg" />
		<image filename="2.jpg" />
		<image filename="3.png" />
		<image filename="4.png" />
		<image filename="5.png" />
	</gallery>
</page>
